#!/usr/bin/env python3
"""This script create ranes.py file for the allisbns project.

How to use this script?

1. Generate and download the RangeMessage.xml file from the International ISBN
Agency website: https://www.isbn-international.org/range_file_generation.
2. Run the following command from the project root:

   uv run python scripts/create-groups-file.py RangeMessage.xml \
     > src/allisbns/ranges.py
"""

import sys

from defusedxml import ElementTree


input_path = sys.argv[1]
root = ElementTree.parse(input_path).getroot()

registration_groups: dict[str, str] = {}
registrant_ranges: dict[str, list[tuple[str, str, int]]] = {}

for group_element in root.findall(".//RegistrationGroups/Group"):
    group_prefix = group_element.find("Prefix").text
    registration_groups[group_prefix] = group_element.find("Agency").text

    group_ranges: list[tuple[str, str, int]] = []
    for rule in group_element.iter("Rule"):
        group_ranges.append(  # noqa: PERF401
            (*rule.find("Range").text.split("-"), int(rule.find("Length").text))
        )
    registrant_ranges[group_prefix] = group_ranges

file_header = """\"\"\"Contains info about registration groups and registrant ranges.

The data is from the RangeMessage.xml file from The International ISBN Agency.

Note: This file is auto-generated by `scripts/create-ranges-file.py`. Please see
an instruction in that file on how to update it.
\"\"\"

__all__ = ["REGISTRATION_GROUPS"]

"""
sys.stdout.writelines(
    [
        file_header,
        "#: ISBN registration groups.\n",
        f"REGISTRATION_GROUPS = {registration_groups!r}\n\n",
        "#: ISBN registrant ranges.\n",
        f"REGISTRANT_RANGES = {registrant_ranges!r}\n",
    ]
)
